[package]
name = "agent-common"
version = "0.0.15"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
testsys-model = { version = "0.0.15", path = "../../model" }
snafu = "0.8"

[dev-dependencies]
tempfile = "3"
