name: Build
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '.github/dependabot.yml'
      - 'bottlerocket/tests/workload/**'
  push:
    paths-ignore:
      - 'docs/**'
      - 'tools/**'
      - '.github/dependabot.yml'
      - 'bottlerocket/tests/workload/**'
    branches: [develop]
jobs:
  build:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_8-core
    steps:
      - uses: actions/checkout@v4
      - run: make sdk-build
        # If we forget to add yamlgen changes to our commits, this will fail.
      - name: ensure that git is clean
        run: test -z "$(git status --untracked-files=all --porcelain)"
      - run: make controller
      - run: make duplicator-resource-agent
      - run: make example-resource-agent
      - run: make example-test-agent
      - run: make example-test-agent-cli
      - run: make integ-test
        env:
          TESTSYS_SELFTEST_SKIP_IMAGE_BUILDS: true
          TESTSYS_SELFTEST_THREADS: 1
