name: Tools
on:
  pull_request:
    paths:
      - 'tools/**'
  push:
    paths:
      - 'tools/**'
    branches: [develop]
jobs:
  images:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_16-core
    steps:
      - uses: actions/checkout@v4
      # Build local tools container in case we are working on a new tools release
      - run: make tools
      - run: make images
